spring.application.name=RMJHallAdmin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Use the single, pre-compiled connection string from Railway and attach 'jdbc:'
spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# --- ORM / HIBERNATE CONFIGURATION ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update