spring.application.name=RMJHallAdmin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# These names must match your Railway Dashboard keys exactly
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# --- ORM / HIBERNATE CONFIGURATION ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update